language: php

php: [5.3, 5.4, 5.5, 5.6, hhvm]

before_script:
  - composer install --dev --prefer-source

script: phpunit -v --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
